import { Bebas_Neue, Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Navigation from "./_components/Navigation";

const fontHeading = Bebas_Neue({
  variable: "--font-heading",
  weight: ["400"],
  subsets: ["latin"],
});

const fontText = Inter({
  variable: "--font-text",
  weight: ["300"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${fontHeading.variable} ${fontText.className} antialiased`}
      >
        <Navigation />
        {children}
      </body>
    </html>
  );
}
